"""This file was generated by xsdata, v23.8, on 2023-10-18 21:20:30

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from typing import List, Optional
from .consultar_nfse_por_rps import (
    TcCancelamentoNfse,
    TcPedidoCancelamento,
)
from .recepcionar_lote_rps import TcListaMensagemRetorno

__NAMESPACE__ = "http://www.betha.com.br/e-nota-contribuinte-ws"


@dataclass
class CancelarNfseEnvio:
    class Meta:
        namespace = "http://www.betha.com.br/e-nota-contribuinte-ws"

    pedido: Optional[TcPedidoCancelamento] = field(
        default=None,
        metadata={
            "name": "Pedido",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class CancelarNfseResposta:
    class Meta:
        name = "cancelarNfseResposta"

    cancelamento: List[TcCancelamentoNfse] = field(
        default_factory=list,
        metadata={
            "name": "Cancelamento",
            "type": "Element",
            "namespace": "",
        }
    )
    lista_mensagem_retorno: List[TcListaMensagemRetorno] = field(
        default_factory=list,
        metadata={
            "name": "ListaMensagemRetorno",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class CancelarNev01CancelarNfseEnvioInput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["CancelarNev01CancelarNfseEnvioInput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        }
    )

    @dataclass
    class Body:
        cancelar_nfse_envio: Optional[CancelarNfseEnvio] = field(
            default=None,
            metadata={
                "name": "CancelarNfseEnvio",
                "type": "Element",
                "namespace": "http://www.betha.com.br/e-nota-contribuinte-ws",
            }
        )


@dataclass
class CancelarNfseEnvioResponse:
    class Meta:
        namespace = "http://www.betha.com.br/e-nota-contribuinte-ws"

    cancelar_nfse_reposta: Optional[CancelarNfseResposta] = field(
        default=None,
        metadata={
            "name": "CancelarNfseReposta",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class CancelarNev01CancelarNfseEnvioOutput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    # Campo `header` Adicionado manualmente.
    # Embora o WSDL não faça menção a nenhum cabeçalho em sua definição,
    # o cabeçalho está sendo incluído na resposta SOAP.
    header: Optional[str] = field(
        default=None,
        metadata={
            "name": "Header",
            "type": "Element",
        }
    )

    body: Optional["CancelarNev01CancelarNfseEnvioOutput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        }
    )

    @dataclass
    class Body:
        cancelar_nfse_envio_response: Optional[CancelarNfseEnvioResponse] = field(
            default=None,
            metadata={
                "name": "CancelarNfseEnvioResponse",
                "type": "Element",
                "namespace": "http://www.betha.com.br/e-nota-contribuinte-ws",
            }
        )
        fault: Optional["CancelarNev01CancelarNfseEnvioOutput.Body.Fault"] = field(
            default=None,
            metadata={
                "name": "Fault",
                "type": "Element",
            }
        )

        @dataclass
        class Fault:
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )


class CancelarNev01CancelarNfseEnvio:
    style = "document"
    location = "http://e-gov.betha.com.br/e-nota-contribuinte-test-ws/cancelarNfse"
    transport = "http://schemas.xmlsoap.org/soap/http"
    input = CancelarNev01CancelarNfseEnvioInput
    output = CancelarNev01CancelarNfseEnvioOutput
