"""This file was generated by xsdata, v23.8, on 2023-10-18 21:20:30

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from typing import List, Optional
from .recepcionar_lote_rps import (
    TcIdentificacaoPrestador,
    TcListaMensagemRetorno,
)

__NAMESPACE__ = "http://www.betha.com.br/e-nota-contribuinte-ws"


@dataclass
class TcTaxaDiversaRetorno:
    class Meta:
        name = "tcTaxaDiversaRetorno"

    codigo: Optional[int] = field(
        default=None,
        metadata={
            "name": "Codigo",
            "type": "Element",
            "namespace": "",
            "required": True,
        }
    )
    descricao: Optional[str] = field(
        default=None,
        metadata={
            "name": "Descricao",
            "type": "Element",
            "namespace": "",
            "required": True,
        }
    )


@dataclass
class ConsultarTaxasDiversasEnvio:
    class Meta:
        namespace = "http://www.betha.com.br/e-nota-contribuinte-ws"

    prestador: Optional[TcIdentificacaoPrestador] = field(
        default=None,
        metadata={
            "name": "Prestador",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class TcListaTaxaDiversaRetorno:
    class Meta:
        name = "tcListaTaxaDiversaRetorno"

    taxa_diversa_retorno: List[TcTaxaDiversaRetorno] = field(
        default_factory=list,
        metadata={
            "name": "TaxaDiversaRetorno",
            "type": "Element",
            "namespace": "",
            "min_occurs": 1,
        }
    )


@dataclass
class ConsultarTaxasDiversasConsultarTaxasDiversasEnvioInput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["ConsultarTaxasDiversasConsultarTaxasDiversasEnvioInput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        }
    )

    @dataclass
    class Body:
        consultar_taxas_diversas_envio: Optional[ConsultarTaxasDiversasEnvio] = field(
            default=None,
            metadata={
                "name": "ConsultarTaxasDiversasEnvio",
                "type": "Element",
                "namespace": "http://www.betha.com.br/e-nota-contribuinte-ws",
            }
        )


@dataclass
class ConsultarTaxasDiversasResposta:
    class Meta:
        name = "consultarTaxasDiversasResposta"

    lista_taxa_diversa_retorno: Optional[TcListaTaxaDiversaRetorno] = field(
        default=None,
        metadata={
            "name": "ListaTaxaDiversaRetorno",
            "type": "Element",
            "namespace": "",
        }
    )
    lista_mensagem_retorno: Optional[TcListaMensagemRetorno] = field(
        default=None,
        metadata={
            "name": "ListaMensagemRetorno",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class ConsultarTaxasDiversasEnvioResponse:
    class Meta:
        namespace = "http://www.betha.com.br/e-nota-contribuinte-ws"

    consultar_taxas_diversas_resposta: Optional[ConsultarTaxasDiversasResposta] = field(
        default=None,
        metadata={
            "name": "ConsultarTaxasDiversasResposta",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class ConsultarTaxasDiversasConsultarTaxasDiversasEnvioOutput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["ConsultarTaxasDiversasConsultarTaxasDiversasEnvioOutput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        }
    )

    @dataclass
    class Body:
        consultar_taxas_diversas_envio_response: Optional[ConsultarTaxasDiversasEnvioResponse] = field(
            default=None,
            metadata={
                "name": "ConsultarTaxasDiversasEnvioResponse",
                "type": "Element",
                "namespace": "http://www.betha.com.br/e-nota-contribuinte-ws",
            }
        )
        fault: Optional["ConsultarTaxasDiversasConsultarTaxasDiversasEnvioOutput.Body.Fault"] = field(
            default=None,
            metadata={
                "name": "Fault",
                "type": "Element",
            }
        )

        @dataclass
        class Fault:
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )


class ConsultarTaxasDiversasConsultarTaxasDiversasEnvio:
    style = "document"
    location = "http://e-gov.betha.com.br/e-nota-contribuinte-test-ws/consultarTaxasDiversas"
    transport = "http://schemas.xmlsoap.org/soap/http"
    input = ConsultarTaxasDiversasConsultarTaxasDiversasEnvioInput
    output = ConsultarTaxasDiversasConsultarTaxasDiversasEnvioOutput
