"""This file was generated by xsdata, v23.8, on 2023-10-18 21:20:30

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""
from dataclasses import dataclass, field
from typing import List, Optional
from xsdata.models.datatype import XmlDateTime
from .consultar_nfse_por_rps import TcCompNfse
from .recepcionar_lote_rps import (
    TcIdentificacaoIntermediarioServico,
    TcIdentificacaoPrestador,
    TcIdentificacaoTomador,
    TcListaMensagemRetorno,
)

__NAMESPACE__ = "http://www.betha.com.br/e-nota-contribuinte-ws"


@dataclass
class TcPeriodoEmissao:
    class Meta:
        name = "tcPeriodoEmissao"

    data_inicial: Optional[XmlDateTime] = field(
        default=None,
        metadata={
            "name": "DataInicial",
            "type": "Element",
            "namespace": "",
            "required": True,
        }
    )
    data_final: Optional[XmlDateTime] = field(
        default=None,
        metadata={
            "name": "DataFinal",
            "type": "Element",
            "namespace": "",
            "required": True,
        }
    )


@dataclass
class ConsultarNfseEnvio:
    class Meta:
        namespace = "http://www.betha.com.br/e-nota-contribuinte-ws"

    prestador: Optional[TcIdentificacaoPrestador] = field(
        default=None,
        metadata={
            "name": "Prestador",
            "type": "Element",
            "namespace": "",
        }
    )
    numero_nfse: Optional[int] = field(
        default=None,
        metadata={
            "name": "NumeroNfse",
            "type": "Element",
            "namespace": "",
        }
    )
    periodo_emissao: Optional[TcPeriodoEmissao] = field(
        default=None,
        metadata={
            "name": "PeriodoEmissao",
            "type": "Element",
            "namespace": "",
        }
    )
    tomador: Optional[TcIdentificacaoTomador] = field(
        default=None,
        metadata={
            "name": "Tomador",
            "type": "Element",
            "namespace": "",
        }
    )
    intermediario_servico: Optional[TcIdentificacaoIntermediarioServico] = field(
        default=None,
        metadata={
            "name": "IntermediarioServico",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class TcListaNfse:
    class Meta:
        name = "tcListaNfse"

    compl_nfse: List[TcCompNfse] = field(
        default_factory=list,
        metadata={
            "name": "ComplNfse",
            "type": "Element",
            "namespace": "",
            "min_occurs": 1,
        }
    )


@dataclass
class ConsultarNeConsultarNfseEnvioInput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["ConsultarNeConsultarNfseEnvioInput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        }
    )

    @dataclass
    class Body:
        consultar_nfse_envio: Optional[ConsultarNfseEnvio] = field(
            default=None,
            metadata={
                "name": "ConsultarNfseEnvio",
                "type": "Element",
                "namespace": "http://www.betha.com.br/e-nota-contribuinte-ws",
            }
        )


@dataclass
class ConsultarNfseResposta1:
    class Meta:
        name = "consultarNfseResposta"

    lista_nfse: Optional[TcListaNfse] = field(
        default=None,
        metadata={
            "name": "ListaNfse",
            "type": "Element",
            "namespace": "",
        }
    )
    lista_mensagem_retorno: Optional[TcListaMensagemRetorno] = field(
        default=None,
        metadata={
            "name": "ListaMensagemRetorno",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class ConsultarNfseEnvioResponse:
    class Meta:
        namespace = "http://www.betha.com.br/e-nota-contribuinte-ws"

    consultar_nfse_resposta: Optional[ConsultarNfseResposta1] = field(
        default=None,
        metadata={
            "name": "ConsultarNfseResposta",
            "type": "Element",
            "namespace": "",
        }
    )


@dataclass
class ConsultarNfseResposta(ConsultarNfseResposta1):
    class Meta:
        namespace = "http://www.betha.com.br/e-nota-contribuinte-ws"


@dataclass
class ConsultarNeConsultarNfseEnvioOutput:
    class Meta:
        name = "Envelope"
        namespace = "http://schemas.xmlsoap.org/soap/envelope/"

    body: Optional["ConsultarNeConsultarNfseEnvioOutput.Body"] = field(
        default=None,
        metadata={
            "name": "Body",
            "type": "Element",
        }
    )

    @dataclass
    class Body:
        consultar_nfse_envio_response: Optional[ConsultarNfseEnvioResponse] = field(
            default=None,
            metadata={
                "name": "ConsultarNfseEnvioResponse",
                "type": "Element",
                "namespace": "http://www.betha.com.br/e-nota-contribuinte-ws",
            }
        )
        fault: Optional["ConsultarNeConsultarNfseEnvioOutput.Body.Fault"] = field(
            default=None,
            metadata={
                "name": "Fault",
                "type": "Element",
            }
        )

        @dataclass
        class Fault:
            faultcode: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            faultstring: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            faultactor: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )
            detail: Optional[str] = field(
                default=None,
                metadata={
                    "type": "Element",
                    "namespace": "",
                }
            )


class ConsultarNeConsultarNfseEnvio:
    style = "document"
    location = "http://e-gov.betha.com.br/e-nota-contribuinte-test-ws/consultarNfse"
    transport = "http://schemas.xmlsoap.org/soap/http"
    input = ConsultarNeConsultarNfseEnvioInput
    output = ConsultarNeConsultarNfseEnvioOutput
